export const products = [
    {
      id: 35,
      name: "Headphones Elite",
      category: "Headphones",
      price: 149,
      description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse eget lectus et elit aliquam eleifend non et lorem. Donec vel massa in massa commodo vulputate id ac purus. Maecenas fringilla efficitur gravida. Phasellus feugiat nulla ac ex suscipit, ut tempor elit facilisis. Ut a mauris ornare, rhoncus libero et, tempus purus. Etiam ultrices aliquet tincidunt. Nullam volutpat auctor enim. Curabitur dapibus ante ac ligula vulputate interdum. Pellentesque id pretium massa. Nulla ac finibus nibh. Nulla facilisi.",
      image: "https://www.audeze.com/cdn/shop/files/ADZ_Maxwell_white_3-Quarters_XB_nooverlay_1200x.jpg?v=1687383866",
    },
    {
      id: 2,
      name: "Smartwatch 3000",
      category: "Watches",
      price:999,
      description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse eget lectus et elit aliquam eleifend non et lorem. Donec vel massa in massa commodo vulputate id ac purus. Maecenas fringilla efficitur gravida. Phasellus feugiat nulla ac ex suscipit, ut tempor elit facilisis. Ut a mauris ornare, rhoncus libero et, tempus purus. Etiam ultrices aliquet tincidunt. Nullam volutpat auctor enim. Curabitur dapibus ante ac ligula vulputate interdum. Pellentesque id pretium massa. Nulla ac finibus nibh. Nulla facilisi.",
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQaZF3MO2n4Wwk2NFhx11q2nmpu9yfn1bnjwg&s",
    },  {
      id: 3,
      name: "Laptop ABC",
      category: "Laptops",
      idFireBase: "Jkx8cMpk754lqpTbqqln",
      price: 799,
      description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse eget lectus et elit aliquam eleifend non et lorem. Donec vel massa in massa commodo vulputate id ac purus. Maecenas fringilla efficitur gravida. Phasellus feugiat nulla ac ex suscipit, ut tempor elit facilisis. Ut a mauris ornare, rhoncus libero et, tempus purus. Etiam ultrices aliquet tincidunt. Nullam volutpat auctor enim. Curabitur dapibus ante ac ligula vulputate interdum. Pellentesque id pretium massa. Nulla ac finibus nibh. Nulla facilisi.",
      image: "https://consumer.huawei.com/content/dam/huawei-cbg-site/latam/latin/mkt/plp/laptops/kv/matebook-14-2021-kv.jpg",
    },{
      id: 4,
      name: "Smartwatch 3000",
      category: "Watches",
      price: 100,
      description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse eget lectus et elit aliquam eleifend non et lorem. Donec vel massa in massa commodo vulputate id ac purus. Maecenas fringilla efficitur gravida. Phasellus feugiat nulla ac ex suscipit, ut tempor elit facilisis. Ut a mauris ornare, rhoncus libero et, tempus purus. Etiam ultrices aliquet tincidunt. Nullam volutpat auctor enim. Curabitur dapibus ante ac ligula vulputate interdum. Pellentesque id pretium massa. Nulla ac finibus nibh. Nulla facilisi.",
      image: "https://www.relojesmania.com/wp-content/uploads/2023/06/richard-mille-nadal.webp",
    },{
      id: 5,
      name: "Laptop rtx2000",
      category: "Laptops",
      price: 400,
      description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse eget lectus et elit aliquam eleifend non et lorem. Donec vel massa in massa commodo vulputate id ac purus. Maecenas fringilla efficitur gravida. Phasellus feugiat nulla ac ex suscipit, ut tempor elit facilisis. Ut a mauris ornare, rhoncus libero et, tempus purus. Etiam ultrices aliquet tincidunt. Nullam volutpat auctor enim. Curabitur dapibus ante ac ligula vulputate interdum. Pellentesque id pretium massa. Nulla ac finibus nibh. Nulla facilisi.",
      image: "https://saudewala.in/cdn/shop/collections/Laptop.jpg?v=1732216115&width=1296",
    },
    {
        id: 1,
        name: "Smartphone XYZ",
        category: "Smartphones",
        price: 299,
        description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse eget lectus et elit aliquam eleifend non et lorem. Donec vel massa in massa commodo vulputate id ac purus. Maecenas fringilla efficitur gravida. Phasellus feugiat nulla ac ex suscipit, ut tempor elit facilisis. Ut a mauris ornare, rhoncus libero et, tempus purus. Etiam ultrices aliquet tincidunt. Nullam volutpat auctor enim. Curabitur dapibus ante ac ligula vulputate interdum. Pellentesque id pretium massa. Nulla ac finibus nibh. Nulla facilisi.",
        image: "https://easy-peasy.ai/cdn-cgi/image/quality=80,format=auto,width=700/https://fdczvxmwwjwpwbeeqcth.supabase.co/storage/v1/object/public/images/e1da98d9-d89e-4dda-a2ad-7bcc30058948/a314e6e9-23f0-4768-ae52-38c8d3709815.png",
      },
      
      {
        id: "aflqFRQyWDVDb5W7WbtF",
        name: "Auriculares Inalambricos In EAR ",
        category: "Headphones",
        price: 300,
        description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse eget lectus et elit aliquam eleifend non et lorem. Donec vel massa in massa commodo vulputate id ac purus. Maecenas fringilla efficitur gravida. Phasellus feugiat nulla ac ex suscipit, ut tempor elit facilisis. Ut a mauris ornare, rhoncus libero et, tempus purus. Etiam ultrices aliquet tincidunt. Nullam volutpat auctor enim. Curabitur dapibus ante ac ligula vulputate interdum. Pellentesque id pretium massa. Nulla ac finibus nibh. Nulla facilisi.",
        image: "https://coppelar.vtexassets.com/arquivos/ids/2002255/1M829188F20240405183533.png?v=638479499877530000",
      },
      {
        id: 4,
        name: "Rolex Yacht-Master 42",
        category: "Watches",
        price:3000,
        description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse eget lectus et elit aliquam eleifend non et lorem. Donec vel massa in massa commodo vulputate id ac purus. Maecenas fringilla efficitur gravida. Phasellus feugiat nulla ac ex suscipit, ut tempor elit facilisis. Ut a mauris ornare, rhoncus libero et, tempus purus. Etiam ultrices aliquet tincidunt. Nullam volutpat auctor enim. Curabitur dapibus ante ac ligula vulputate interdum. Pellentesque id pretium massa. Nulla ac finibus nibh. Nulla facilisi.",
        image: "https://i.ytimg.com/vi_webp/G9tJGCsTn3o/maxresdefault.webp",
      },
      {
        id: 5,
        name: "Mouse Pad Gamer Led Rgb ",
        category: "Watches",
        price: 250,
        description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse eget lectus et elit aliquam eleifend non et lorem. Donec vel massa in massa commodo vulputate id ac purus. Maecenas fringilla efficitur gravida. Phasellus feugiat nulla ac ex suscipit, ut tempor elit facilisis. Ut a mauris ornare, rhoncus libero et, tempus purus. Etiam ultrices aliquet tincidunt. Nullam volutpat auctor enim. Curabitur dapibus ante ac ligula vulputate interdum. Pellentesque id pretium massa. Nulla ac finibus nibh. Nulla facilisi.",
        image:"https://http2.mlstatic.com/D_NQ_NP_932905-MLA49410468832_032022-O.webp",
      },
      {
        id: 6,
        name: "Smartwatch 3000",
        category: "Laptops",
        price: 777,
        description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse eget lectus et elit aliquam eleifend non et lorem. Donec vel massa in massa commodo vulputate id ac purus. Maecenas fringilla efficitur gravida. Phasellus feugiat nulla ac ex suscipit, ut tempor elit facilisis. Ut a mauris ornare, rhoncus libero et, tempus purus. Etiam ultrices aliquet tincidunt. Nullam volutpat auctor enim. Curabitur dapibus ante ac ligula vulputate interdum. Pellentesque id pretium massa. Nulla ac finibus nibh. Nulla facilisi.",
        image: "https://i.pcmag.com/imagery/reviews/043DROGFihmSgG7S6LUb006-1..v1709854231.jpg",
      },
      {
        id: 7,
        name: "Smartwatch 3000",
        category: "Watches",
        price:300,
        description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse eget lectus et elit aliquam eleifend non et lorem. Donec vel massa in massa commodo vulputate id ac purus. Maecenas fringilla efficitur gravida. Phasellus feugiat nulla ac ex suscipit, ut tempor elit facilisis. Ut a mauris ornare, rhoncus libero et, tempus purus. Etiam ultrices aliquet tincidunt. Nullam volutpat auctor enim. Curabitur dapibus ante ac ligula vulputate interdum. Pellentesque id pretium massa. Nulla ac finibus nibh. Nulla facilisi.",
        image: "https://gestion.pe/resizer/Owt5ch7klp_3tx8ZOFNroPCxbQM=/1200x1200/smart/filters:format(jpeg):quality(75)/arc-anglerfish-arc2-prod-elcomercio.s3.amazonaws.com/public/PSLCPMPAOBAKRA4QFLIXL7G75Q.jpg",
      },
      {
        id: 8,
        name: "Smartwatch 3000",
        category: "Headphones",
        price: 239,
        description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse eget lectus et elit aliquam eleifend non et lorem. Donec vel massa in massa commodo vulputate id ac purus. Maecenas fringilla efficitur gravida. Phasellus feugiat nulla ac ex suscipit, ut tempor elit facilisis. Ut a mauris ornare, rhoncus libero et, tempus purus. Etiam ultrices aliquet tincidunt. Nullam volutpat auctor enim. Curabitur dapibus ante ac ligula vulputate interdum. Pellentesque id pretium massa. Nulla ac finibus nibh. Nulla facilisi.",
        image: "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/MQTQ3?wid=1144&hei=1144&fmt=jpeg&qlt=90&.v=1687660671363",
      },
      {
        id: 9,
        name: "Galaxy Z Flip5",
        category: "Smartphones",
        price: 777,
        description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse eget lectus et elit aliquam eleifend non et lorem. Donec vel massa in massa commodo vulputate id ac purus. Maecenas fringilla efficitur gravida. Phasellus feugiat nulla ac ex suscipit, ut tempor elit facilisis. Ut a mauris ornare, rhoncus libero et, tempus purus. Etiam ultrices aliquet tincidunt. Nullam volutpat auctor enim. Curabitur dapibus ante ac ligula vulputate interdum. Pellentesque id pretium massa. Nulla ac finibus nibh. Nulla facilisi.",
        image: "https://multipoint.com.ar/Image/0/700_700-i14.jpg",
      },
      {
        id: 10,
        name: "Auricular inalambrico Beats Studio Pro -",
        category: "Headphones",
        price: 239,
        description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse eget lectus et elit aliquam eleifend non et lorem. Donec vel massa in massa commodo vulputate id ac purus. Maecenas fringilla efficitur gravida. Phasellus feugiat nulla ac ex suscipit, ut tempor elit facilisis. Ut a mauris ornare, rhoncus libero et, tempus purus. Etiam ultrices aliquet tincidunt. Nullam volutpat auctor enim. Curabitur dapibus ante ac ligula vulputate interdum. Pellentesque id pretium massa. Nulla ac finibus nibh. Nulla facilisi.",
        image: "https://www.armytech.com.ar/3300-large_default/auricular-inalambrico-beats-studio-pro-outlet.jpg",
      },
      {
        id: 11,
        name: "Notebook Hp 15",
        category: "laptops",
        price: 299,
        description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse eget lectus et elit aliquam eleifend non et lorem. Donec vel massa in massa commodo vulputate id ac purus. Maecenas fringilla efficitur gravida. Phasellus feugiat nulla ac ex suscipit, ut tempor elit facilisis. Ut a mauris ornare, rhoncus libero et, tempus purus. Etiam ultrices aliquet tincidunt. Nullam volutpat auctor enim. Curabitur dapibus ante ac ligula vulputate interdum. Pellentesque id pretium massa. Nulla ac finibus nibh. Nulla facilisi.",
        image: "https://http2.mlstatic.com/D_NQ_NP_604233-MLA79955329254_102024-O.webp",
      },
      {
        id: 12,
        name: "Apple MacBook Pro 13.3",
        category: "Laptops",
        price: 650,
        description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse eget lectus et elit aliquam eleifend non et lorem. Donec vel massa in massa commodo vulputate id ac purus. Maecenas fringilla efficitur gravida. Phasellus feugiat nulla ac ex suscipit, ut tempor elit facilisis. Ut a mauris ornare, rhoncus libero et, tempus purus. Etiam ultrices aliquet tincidunt. Nullam volutpat auctor enim. Curabitur dapibus ante ac ligula vulputate interdum. Pellentesque id pretium massa. Nulla ac finibus nibh. Nulla facilisi.",
        image: "https://lidernotebooks.com.ar/wp-content/uploads/2022/05/Apple-MacBook-Pro-Apple-M1-MYD82LL-A_0005_1605032111_165615604809-600x600.jpg",
      },
      {
        id: 13,
        name: "Auriculares Bluetooth",
        category: "Headphones",
        price: 400,
        description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse eget lectus et elit aliquam eleifend non et lorem. Donec vel massa in massa commodo vulputate id ac purus. Maecenas fringilla efficitur gravida. Phasellus feugiat nulla ac ex suscipit, ut tempor elit facilisis. Ut a mauris ornare, rhoncus libero et, tempus purus. Etiam ultrices aliquet tincidunt. Nullam volutpat auctor enim. Curabitur dapibus ante ac ligula vulputate interdum. Pellentesque id pretium massa. Nulla ac finibus nibh. Nulla facilisi.",
        image: "https://acdn.mitiendanube.com/stores/884/018/products/gamma-hogar-2022-10-25t104326-7711-f545577cf5cc3a201b16667059054363-480-0.webp",
      },{
        id: 14,
        name: "Smartwatch Unisex Zl02c",
        category: "Watches",
        price: 199,
        description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse eget lectus et elit aliquam eleifend non et lorem. Donec vel massa in massa commodo vulputate id ac purus. Maecenas fringilla efficitur gravida. Phasellus feugiat nulla ac ex suscipit, ut tempor elit facilisis. Ut a mauris ornare, rhoncus libero et, tempus purus. Etiam ultrices aliquet tincidunt. Nullam volutpat auctor enim. Curabitur dapibus ante ac ligula vulputate interdum. Pellentesque id pretium massa. Nulla ac finibus nibh. Nulla facilisi.",
        image: "https://http2.mlstatic.com/D_NQ_NP_856423-MLU73118496384_122023-O.webp",
      },{
        id: 15,
        name: "Celular Samsung Galaxy A06",
        category: "Smartphones",
        price: 799,
        description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse eget lectus et elit aliquam eleifend non et lorem. Donec vel massa in massa commodo vulputate id ac purus. Maecenas fringilla efficitur gravida. Phasellus feugiat nulla ac ex suscipit, ut tempor elit facilisis. Ut a mauris ornare, rhoncus libero et, tempus purus. Etiam ultrices aliquet tincidunt. Nullam volutpat auctor enim. Curabitur dapibus ante ac ligula vulputate interdum. Pellentesque id pretium massa. Nulla ac finibus nibh. Nulla facilisi.",
        image: "https://www.cetrogar.com.ar/media/catalog/product/4/_/4_a06_blueblack_frontback_1.png?width=500&height=500&canvas=500,500&quality=80&bg-color=255,255,255&fit=bounds",
      },{
        id: 16,
        name: "Smartwatch 3000",
        category: "Laptops",
        price: 459,
        description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse eget lectus et elit aliquam eleifend non et lorem. Donec vel massa in massa commodo vulputate id ac purus. Maecenas fringilla efficitur gravida. Phasellus feugiat nulla ac ex suscipit, ut tempor elit facilisis. Ut a mauris ornare, rhoncus libero et, tempus purus. Etiam ultrices aliquet tincidunt. Nullam volutpat auctor enim. Curabitur dapibus ante ac ligula vulputate interdum. Pellentesque id pretium massa. Nulla ac finibus nibh. Nulla facilisi.",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRMwfpGfS0knB3d9BikykO7ucGbFFZkQ1GG8g&s"
  ,
      },{
        id: 17,
        name: "Smartwatch DT2",
        category: "Watches",
        price:300,
        description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse eget lectus et elit aliquam eleifend non et lorem. Donec vel massa in massa commodo vulputate id ac purus. Maecenas fringilla efficitur gravida. Phasellus feugiat nulla ac ex suscipit, ut tempor elit facilisis. Ut a mauris ornare, rhoncus libero et, tempus purus. Etiam ultrices aliquet tincidunt. Nullam volutpat auctor enim. Curabitur dapibus ante ac ligula vulputate interdum. Pellentesque id pretium massa. Nulla ac finibus nibh. Nulla facilisi.",
        image: "https://acdn.mitiendanube.com/stores/001/085/544/products/smartwatch-dt2-91-92ac946130428fcc0c16692121376758-640-0.webp",
      },{
        id: 18,
        name: "Higolepc mini pc win 11",
        category: "Laptops",
        price: 199,
        description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse eget lectus et elit aliquam eleifend non et lorem. Donec vel massa in massa commodo vulputate id ac purus. Maecenas fringilla efficitur gravida. Phasellus feugiat nulla ac ex suscipit, ut tempor elit facilisis. Ut a mauris ornare, rhoncus libero et, tempus purus. Etiam ultrices aliquet tincidunt. Nullam volutpat auctor enim. Curabitur dapibus ante ac ligula vulputate interdum. Pellentesque id pretium massa. Nulla ac finibus nibh. Nulla facilisi.",
        image: "https://m.media-amazon.com/images/I/613Znn6NwpL._AC_SL1500_.jpg",
      },{
        id: 34,
        name: "Mini PC Completa Cubic",
        category: "Laptops",
        price: 459,
        description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse eget lectus et elit aliquam eleifend non et lorem. Donec vel massa in massa commodo vulputate id ac purus. Maecenas fringilla efficitur gravida. Phasellus feugiat nulla ac ex suscipit, ut tempor elit facilisis. Ut a mauris ornare, rhoncus libero et, tempus purus. Etiam ultrices aliquet tincidunt. Nullam volutpat auctor enim. Curabitur dapibus ante ac ligula vulputate interdum. Pellentesque id pretium massa. Nulla ac finibus nibh. Nulla facilisi.",
        image: "https://bangho.vtexassets.com/arquivos/ids/161366/mini-pc-cubic-a80-completa-1.jpg?v=638126723204700000",
      },{
        id: 19,
        name: "Celular Tecno Spark 20C",
        category: "Smartphones",
        price: 239,
        description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse eget lectus et elit aliquam eleifend non et lorem. Donec vel massa in massa commodo vulputate id ac purus. Maecenas fringilla efficitur gravida. Phasellus feugiat nulla ac ex suscipit, ut tempor elit facilisis. Ut a mauris ornare, rhoncus libero et, tempus purus. Etiam ultrices aliquet tincidunt. Nullam volutpat auctor enim. Curabitur dapibus ante ac ligula vulputate interdum. Pellentesque id pretium massa. Nulla ac finibus nibh. Nulla facilisi.",
        image: "https://pardohogar.vtexassets.com/arquivos/ids/200299/Celular-Tecno-Spark-20C-128GB-4GB-Verde2.jpg?v=638590616985530000",
      },{
        id: 20,
        name: "Auricular Bluetooth",
        category: "Headphones",
        price: 799,
        description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse eget lectus et elit aliquam eleifend non et lorem. Donec vel massa in massa commodo vulputate id ac purus. Maecenas fringilla efficitur gravida. Phasellus feugiat nulla ac ex suscipit, ut tempor elit facilisis. Ut a mauris ornare, rhoncus libero et, tempus purus. Etiam ultrices aliquet tincidunt. Nullam volutpat auctor enim. Curabitur dapibus ante ac ligula vulputate interdum. Pellentesque id pretium massa. Nulla ac finibus nibh. Nulla facilisi.",
        image: "https://dcdn.mitiendanube.com/stores/004/834/971/products/1-de269f649248dcb57517190885633324-480-0.webp",
      },{
        id: 21,
        name: "Reloj Inteligente Amazfit",
        category: "Watches",
        price: 900,
        description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse eget lectus et elit aliquam eleifend non et lorem. Donec vel massa in massa commodo vulputate id ac purus. Maecenas fringilla efficitur gravida. Phasellus feugiat nulla ac ex suscipit, ut tempor elit facilisis. Ut a mauris ornare, rhoncus libero et, tempus purus. Etiam ultrices aliquet tincidunt. Nullam volutpat auctor enim. Curabitur dapibus ante ac ligula vulputate interdum. Pellentesque id pretium massa. Nulla ac finibus nibh. Nulla facilisi.",
        image: "https://http2.mlstatic.com/D_NQ_NP_743425-MLA50712256599_072022-O.webp",
      },{
        id: 22,
        name: "Xiaomi Redmi A3X:",
        category: "Smartphones",
        price: 1000,
        description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse eget lectus et elit aliquam eleifend non et lorem. Donec vel massa in massa commodo vulputate id ac purus. Maecenas fringilla efficitur gravida. Phasellus feugiat nulla ac ex suscipit, ut tempor elit facilisis. Ut a mauris ornare, rhoncus libero et, tempus purus. Etiam ultrices aliquet tincidunt. Nullam volutpat auctor enim. Curabitur dapibus ante ac ligula vulputate interdum. Pellentesque id pretium massa. Nulla ac finibus nibh. Nulla facilisi.",
        image: "https://acdn.mitiendanube.com/stores/001/643/020/products/redmi-a3x-verde-f2a068d88c0006752217271237050244-1024-1024.png",
      },{
        id: 23,
        name: "Notebook ASUS Vivobook",
        category: "Laptops",
        price: 620,
        description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse eget lectus et elit aliquam eleifend non et lorem. Donec vel massa in massa commodo vulputate id ac purus. Maecenas fringilla efficitur gravida. Phasellus feugiat nulla ac ex suscipit, ut tempor elit facilisis. Ut a mauris ornare, rhoncus libero et, tempus purus. Etiam ultrices aliquet tincidunt. Nullam volutpat auctor enim. Curabitur dapibus ante ac ligula vulputate interdum. Pellentesque id pretium massa. Nulla ac finibus nibh. Nulla facilisi.",
        image: "https://static.bidcom.com.ar/publicacionesML/productos/NOT00231/1000x1000-NOT00231.jpg",
      },{
        id: 24,
        name: "Smartwatch Scs",
        category: "Watches",
        price: 350,
        description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse eget lectus et elit aliquam eleifend non et lorem. Donec vel massa in massa commodo vulputate id ac purus. Maecenas fringilla efficitur gravida. Phasellus feugiat nulla ac ex suscipit, ut tempor elit facilisis. Ut a mauris ornare, rhoncus libero et, tempus purus. Etiam ultrices aliquet tincidunt. Nullam volutpat auctor enim. Curabitur dapibus ante ac ligula vulputate interdum. Pellentesque id pretium massa. Nulla ac finibus nibh. Nulla facilisi.",
        image: "https://calzadosnicoar.vtexassets.com/arquivos/ids/88001640/reloj-smartwatch-f16-ultra-b_ecwhdj.jpg?v=638599381209270000",
      },{
        id: 25,
        name: "KZ Edx-bk Auricular",
        category: "Headphones",
        price: 800,
        description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse eget lectus et elit aliquam eleifend non et lorem. Donec vel massa in massa commodo vulputate id ac purus. Maecenas fringilla efficitur gravida. Phasellus feugiat nulla ac ex suscipit, ut tempor elit facilisis. Ut a mauris ornare, rhoncus libero et, tempus purus. Etiam ultrices aliquet tincidunt. Nullam volutpat auctor enim. Curabitur dapibus ante ac ligula vulputate interdum. Pellentesque id pretium massa. Nulla ac finibus nibh. Nulla facilisi.",
        image: "https://www.heavenimagenes.com/heavencommerce/36552d98-557c-43dd-ad26-2c9343813a85/images/v2/KZ/17034_medium.jpg",
      },{
        id: 26,
        name: "Apple iPhone 14",
        category: "Smartphones",
        price: 1200,
        description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse eget lectus et elit aliquam eleifend non et lorem. Donec vel massa in massa commodo vulputate id ac purus. Maecenas fringilla efficitur gravida. Phasellus feugiat nulla ac ex suscipit, ut tempor elit facilisis. Ut a mauris ornare, rhoncus libero et, tempus purus. Etiam ultrices aliquet tincidunt. Nullam volutpat auctor enim. Curabitur dapibus ante ac ligula vulputate interdum. Pellentesque id pretium massa. Nulla ac finibus nibh. Nulla facilisi.",
        image: "https://http2.mlstatic.com/D_Q_NP_864844-MLM51559388062_092022-O.webp",
      },{
        id: 27,
        name: "Monitor 4K Thunderbolt 4",
        category: "Laptops",
        price: 900,
        description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse eget lectus et elit aliquam eleifend non et lorem. Donec vel massa in massa commodo vulputate id ac purus. Maecenas fringilla efficitur gravida. Phasellus feugiat nulla ac ex suscipit, ut tempor elit facilisis. Ut a mauris ornare, rhoncus libero et, tempus purus. Etiam ultrices aliquet tincidunt. Nullam volutpat auctor enim. Curabitur dapibus ante ac ligula vulputate interdum. Pellentesque id pretium massa. Nulla ac finibus nibh. Nulla facilisi.",
        image: "https://ssl-product-images.www8-hp.com/digmedialib/prodimg/lowres/c08894694.png",
      },{
        id: 28,
        name: "Auricular In-Ear Motorola",
        category: "Headphones",
        price: 235,
        description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse eget lectus et elit aliquam eleifend non et lorem. Donec vel massa in massa commodo vulputate id ac purus. Maecenas fringilla efficitur gravida. Phasellus feugiat nulla ac ex suscipit, ut tempor elit facilisis. Ut a mauris ornare, rhoncus libero et, tempus purus. Etiam ultrices aliquet tincidunt. Nullam volutpat auctor enim. Curabitur dapibus ante ac ligula vulputate interdum. Pellentesque id pretium massa. Nulla ac finibus nibh. Nulla facilisi.",
        image: "https://tiendadiggit.com.ar/web/image/product.image/8557/image_1024/Auriculares%20In-ear%20Bluetooth%20Motorola%20Moto%20Buds%20105%20Negro?unique=95a9818",
      },{
        id: 29,
        name: "Reloj Casio Vintage A",
        category: "Watches",
        price: 700,
        description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse eget lectus et elit aliquam eleifend non et lorem. Donec vel massa in massa commodo vulputate id ac purus. Maecenas fringilla efficitur gravida. Phasellus feugiat nulla ac ex suscipit, ut tempor elit facilisis. Ut a mauris ornare, rhoncus libero et, tempus purus. Etiam ultrices aliquet tincidunt. Nullam volutpat auctor enim. Curabitur dapibus ante ac ligula vulputate interdum. Pellentesque id pretium massa. Nulla ac finibus nibh. Nulla facilisi.",
        image: "https://acdn.mitiendanube.com/stores/001/417/925/products/imagen_2022-02-16_0948191-7a32a2bfef801a3ee916450157668305-640-0.png",
      },{
        id: 30,
        name: "iPhone SE 128 GB -",
        category: "Smartphones",
        price: 999,
        description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse eget lectus et elit aliquam eleifend non et lorem. Donec vel massa in massa commodo vulputate id ac purus. Maecenas fringilla efficitur gravida. Phasellus feugiat nulla ac ex suscipit, ut tempor elit facilisis. Ut a mauris ornare, rhoncus libero et, tempus purus. Etiam ultrices aliquet tincidunt. Nullam volutpat auctor enim. Curabitur dapibus ante ac ligula vulputate interdum. Pellentesque id pretium massa. Nulla ac finibus nibh. Nulla facilisi.",
        image: "https://www.macstation.com.ar/web/image/product.template/8645/image_1920?unique=ccc442c",
      },{
        id: 31,
        name: "MOUSE LOGITECH G203",
        category: "Laptops",
        price: 600,
        description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse eget lectus et elit aliquam eleifend non et lorem. Donec vel massa in massa commodo vulputate id ac purus. Maecenas fringilla efficitur gravida. Phasellus feugiat nulla ac ex suscipit, ut tempor elit facilisis. Ut a mauris ornare, rhoncus libero et, tempus purus. Etiam ultrices aliquet tincidunt. Nullam volutpat auctor enim. Curabitur dapibus ante ac ligula vulputate interdum. Pellentesque id pretium massa. Nulla ac finibus nibh. Nulla facilisi.",
        image: "https://www.xt-pc.com.ar/img/productos/14/MOU454.jpg",
      },{
        id: 32,
        name: "Auriculares Xiaomi Basic",
        category: "Headphones",
        price: 1150,
        description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse eget lectus et elit aliquam eleifend non et lorem. Donec vel massa in massa commodo vulputate id ac purus. Maecenas fringilla efficitur gravida. Phasellus feugiat nulla ac ex suscipit, ut tempor elit facilisis. Ut a mauris ornare, rhoncus libero et, tempus purus. Etiam ultrices aliquet tincidunt. Nullam volutpat auctor enim. Curabitur dapibus ante ac ligula vulputate interdum. Pellentesque id pretium massa. Nulla ac finibus nibh. Nulla facilisi.",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTvGeIvI6yo0N7zxtiOKV4HPos57pcVv6_fyg&s",
      },
      {
        id: 33,
        name: "Smartwatch 3000",
        category: "Watches",
        price: 2000,
        description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse eget lectus et elit aliquam eleifend non et lorem. Donec vel massa in massa commodo vulputate id ac purus. Maecenas fringilla efficitur gravida. Phasellus feugiat nulla ac ex suscipit, ut tempor elit facilisis. Ut a mauris ornare, rhoncus libero et, tempus purus. Etiam ultrices aliquet tincidunt. Nullam volutpat auctor enim. Curabitur dapibus ante ac ligula vulputate interdum. Pellentesque id pretium massa. Nulla ac finibus nibh. Nulla facilisi.",
        image: "https://www.joyeriaperret.com.ar/wp-content/uploads/2024/05/m126610ln-0001_drp-upright-bba-with-shadow.webp",
      },
      
  
    ];
  
  
    