
const products = [
    {
      id: 1,
      name: "Smartphone XYZ",
      category: "Smartphones",
      price: 299,
      description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse eget lectus et elit aliquam eleifend non et lorem. Donec vel massa in massa commodo vulputate id ac purus. Maecenas fringilla efficitur gravida. Phasellus feugiat nulla ac ex suscipit, ut tempor elit facilisis. Ut a mauris ornare, rhoncus libero et, tempus purus. Etiam ultrices aliquet tincidunt. Nullam volutpat auctor enim. Curabitur dapibus ante ac ligula vulputate interdum. Pellentesque id pretium massa. Nulla ac finibus nibh. Nulla facilisi.",
      image: "https://easy-peasy.ai/cdn-cgi/image/quality=80,format=auto,width=700/https://fdczvxmwwjwpwbeeqcth.supabase.co/storage/v1/object/public/images/e1da98d9-d89e-4dda-a2ad-7bcc30058948/a314e6e9-23f0-4768-ae52-38c8d3709815.png",
    },
    {
      id: 2,
      name: "Laptop ABC",
      category: "Laptops",
      price: 799,
      description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse eget lectus et elit aliquam eleifend non et lorem. Donec vel massa in massa commodo vulputate id ac purus. Maecenas fringilla efficitur gravida. Phasellus feugiat nulla ac ex suscipit, ut tempor elit facilisis. Ut a mauris ornare, rhoncus libero et, tempus purus. Etiam ultrices aliquet tincidunt. Nullam volutpat auctor enim. Curabitur dapibus ante ac ligula vulputate interdum. Pellentesque id pretium massa. Nulla ac finibus nibh. Nulla facilisi.",
      image: "https://consumer.huawei.com/content/dam/huawei-cbg-site/latam/latin/mkt/plp/laptops/kv/matebook-14-2021-kv.jpg",
    },
    {
      id: 3,
      name: "Headphones Elite",
      category: "Headphones",
      price: 149,
      description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse eget lectus et elit aliquam eleifend non et lorem. Donec vel massa in massa commodo vulputate id ac purus. Maecenas fringilla efficitur gravida. Phasellus feugiat nulla ac ex suscipit, ut tempor elit facilisis. Ut a mauris ornare, rhoncus libero et, tempus purus. Etiam ultrices aliquet tincidunt. Nullam volutpat auctor enim. Curabitur dapibus ante ac ligula vulputate interdum. Pellentesque id pretium massa. Nulla ac finibus nibh. Nulla facilisi.",
      image: "https://www.audeze.com/cdn/shop/files/ADZ_Maxwell_white_3-Quarters_XB_nooverlay_1200x.jpg?v=1687383866",
    },
    {
      id: 4,
      name: "Smartwatch 3000",
      category: "Watches",
      price:999,
      description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse eget lectus et elit aliquam eleifend non et lorem. Donec vel massa in massa commodo vulputate id ac purus. Maecenas fringilla efficitur gravida. Phasellus feugiat nulla ac ex suscipit, ut tempor elit facilisis. Ut a mauris ornare, rhoncus libero et, tempus purus. Etiam ultrices aliquet tincidunt. Nullam volutpat auctor enim. Curabitur dapibus ante ac ligula vulputate interdum. Pellentesque id pretium massa. Nulla ac finibus nibh. Nulla facilisi.",
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQaZF3MO2n4Wwk2NFhx11q2nmpu9yfn1bnjwg&s",
    },
    {
      id: 5,
      name: "Smartwatch 3000",
      category: "Watches",
      price: 20,
      description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse eget lectus et elit aliquam eleifend non et lorem. Donec vel massa in massa commodo vulputate id ac purus. Maecenas fringilla efficitur gravida. Phasellus feugiat nulla ac ex suscipit, ut tempor elit facilisis. Ut a mauris ornare, rhoncus libero et, tempus purus. Etiam ultrices aliquet tincidunt. Nullam volutpat auctor enim. Curabitur dapibus ante ac ligula vulputate interdum. Pellentesque id pretium massa. Nulla ac finibus nibh. Nulla facilisi.",
      image:"https://saudewala.in/cdn/shop/collections/Laptop.jpg?v=1732216115&width=1296",
    },
    {
      id: 6,
      name: "Smartwatch 3000",
      category: "Watches",
      price: 100,
      description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse eget lectus et elit aliquam eleifend non et lorem. Donec vel massa in massa commodo vulputate id ac purus. Maecenas fringilla efficitur gravida. Phasellus feugiat nulla ac ex suscipit, ut tempor elit facilisis. Ut a mauris ornare, rhoncus libero et, tempus purus. Etiam ultrices aliquet tincidunt. Nullam volutpat auctor enim. Curabitur dapibus ante ac ligula vulputate interdum. Pellentesque id pretium massa. Nulla ac finibus nibh. Nulla facilisi.",
      image: "https://www.relojesmania.com/wp-content/uploads/2023/06/richard-mille-nadal.webp",
    },
    {
      id: 7,
      name: "Smartwatch 3000",
      category: "Laptops",
      price: 400,
      description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse eget lectus et elit aliquam eleifend non et lorem. Donec vel massa in massa commodo vulputate id ac purus. Maecenas fringilla efficitur gravida. Phasellus feugiat nulla ac ex suscipit, ut tempor elit facilisis. Ut a mauris ornare, rhoncus libero et, tempus purus. Etiam ultrices aliquet tincidunt. Nullam volutpat auctor enim. Curabitur dapibus ante ac ligula vulputate interdum. Pellentesque id pretium massa. Nulla ac finibus nibh. Nulla facilisi.",
      image: "https://saudewala.in/cdn/shop/collections/Laptop.jpg?v=1732216115&width=1296",
    },
    {
      id: 8,
      name: "Smartwatch 3000",
      category: "Headphones",
      price: 239,
      description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse eget lectus et elit aliquam eleifend non et lorem. Donec vel massa in massa commodo vulputate id ac purus. Maecenas fringilla efficitur gravida. Phasellus feugiat nulla ac ex suscipit, ut tempor elit facilisis. Ut a mauris ornare, rhoncus libero et, tempus purus. Etiam ultrices aliquet tincidunt. Nullam volutpat auctor enim. Curabitur dapibus ante ac ligula vulputate interdum. Pellentesque id pretium massa. Nulla ac finibus nibh. Nulla facilisi.",
      image: "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/MQTQ3?wid=1144&hei=1144&fmt=jpeg&qlt=90&.v=1687660671363",
    },
    {
      id: 9,
      name: "Smartwatch 3000",
      category: "Laptops",
      price: 459,
      description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse eget lectus et elit aliquam eleifend non et lorem. Donec vel massa in massa commodo vulputate id ac purus. Maecenas fringilla efficitur gravida. Phasellus feugiat nulla ac ex suscipit, ut tempor elit facilisis. Ut a mauris ornare, rhoncus libero et, tempus purus. Etiam ultrices aliquet tincidunt. Nullam volutpat auctor enim. Curabitur dapibus ante ac ligula vulputate interdum. Pellentesque id pretium massa. Nulla ac finibus nibh. Nulla facilisi.",
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRMwfpGfS0knB3d9BikykO7ucGbFFZkQ1GG8g&s",
    },
    {
      id: 10,
      name: "Smartwatch 3000",
      category: "Laptops",
      price: 199,
      description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse eget lectus et elit aliquam eleifend non et lorem. Donec vel massa in massa commodo vulputate id ac purus. Maecenas fringilla efficitur gravida. Phasellus feugiat nulla ac ex suscipit, ut tempor elit facilisis. Ut a mauris ornare, rhoncus libero et, tempus purus. Etiam ultrices aliquet tincidunt. Nullam volutpat auctor enim. Curabitur dapibus ante ac ligula vulputate interdum. Pellentesque id pretium massa. Nulla ac finibus nibh. Nulla facilisi.",
      image: "https://hiraoka.com.pe/media/wysiwyg/cat-laptop-baratas.png",
    },
    {
      id: 11,
      name: "Smartwatch 3000",
      category: "Watches",
      price: 699,
      description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse eget lectus et elit aliquam eleifend non et lorem. Donec vel massa in massa commodo vulputate id ac purus. Maecenas fringilla efficitur gravida. Phasellus feugiat nulla ac ex suscipit, ut tempor elit facilisis. Ut a mauris ornare, rhoncus libero et, tempus purus. Etiam ultrices aliquet tincidunt. Nullam volutpat auctor enim. Curabitur dapibus ante ac ligula vulputate interdum. Pellentesque id pretium massa. Nulla ac finibus nibh. Nulla facilisi.",
      image: "https://i.kinja-img.com/image/upload/c_fit,q_60,w_645/74b7e2b904f469e1d4b2811030f83eba.jpg",
    },
    {
      id: 12,
      name: "Smartwatch 3000",
      category: "Watches",
      price:300,
      description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse eget lectus et elit aliquam eleifend non et lorem. Donec vel massa in massa commodo vulputate id ac purus. Maecenas fringilla efficitur gravida. Phasellus feugiat nulla ac ex suscipit, ut tempor elit facilisis. Ut a mauris ornare, rhoncus libero et, tempus purus. Etiam ultrices aliquet tincidunt. Nullam volutpat auctor enim. Curabitur dapibus ante ac ligula vulputate interdum. Pellentesque id pretium massa. Nulla ac finibus nibh. Nulla facilisi.",
      image: "https://gestion.pe/resizer/Owt5ch7klp_3tx8ZOFNroPCxbQM=/1200x1200/smart/filters:format(jpeg):quality(75)/arc-anglerfish-arc2-prod-elcomercio.s3.amazonaws.com/public/PSLCPMPAOBAKRA4QFLIXL7G75Q.jpg",
    },
    {
      id: 13,
      name: "Smartwatch 3000",
      category: "Laptops",
      price: 777,
      description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse eget lectus et elit aliquam eleifend non et lorem. Donec vel massa in massa commodo vulputate id ac purus. Maecenas fringilla efficitur gravida. Phasellus feugiat nulla ac ex suscipit, ut tempor elit facilisis. Ut a mauris ornare, rhoncus libero et, tempus purus. Etiam ultrices aliquet tincidunt. Nullam volutpat auctor enim. Curabitur dapibus ante ac ligula vulputate interdum. Pellentesque id pretium massa. Nulla ac finibus nibh. Nulla facilisi.",
      image: "https://i.pcmag.com/imagery/reviews/043DROGFihmSgG7S6LUb006-1..v1709854231.jpg",
    },
    

  ];
  
  export default products;